replicaCount: 1
image:
  repository: lmenezes/cerebro
  tag: 0.8.5
config:
  hosts:
    - host: http://elasticsearch-master:9200
      name: elastic
resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1Gi
ingress:
  enabled: true
  hosts:
  - cerebro.k8.iprod.local
