all:
  hosts:
    k8s01:
      ansible_host: 159.122.111.56
      ansible_user: root
      ip: 159.122.111.56
      access_ip: 159.122.111.56
    k8s02:
      ansible_host: 159.122.111.53
      ansible_user: root
      ip: 159.122.111.53
      access_ip: 159.122.111.53
    k8s03:
      ansible_host: 159.122.111.51
      ansible_user: root
      ip: 159.122.111.51
      access_ip: 159.122.111.51
    k8s04:
      ansible_host: 159.122.111.55
      ansible_user: root
      ip: 159.122.111.55
      access_ip: 159.122.111.55
    k8s05:
      ansible_host: 159.122.111.54
      ansible_user: root
      ip: 159.122.111.54
      access_ip: 159.122.111.54
  children:
    kube-master:
      hosts:
        k8s01:
        k8s02:
    kube-node:
      hosts:
        k8s01:
        k8s02:
        k8s03:
        k8s04:
        k8s05:
    etcd:
      hosts:
        k8s01:
        k8s02:
        k8s03:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
    glusterfs:
      hosts:
        k8s01:
        k8s02:
        k8s03:
  vars:
    glusterfs_brick_dir: "/srv/glusterfs/bricks"
