apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: chartmuseum-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: charts.k8.mmi.local
    http:
      paths:
      - path: /
        backend:
          serviceName: chartmuseum-chartmuseum
          servicePort: 8080
