image:
  repository: "chartmuseum/chartmuseum"
  tag: "v0.11.0"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 32Mi
persistence:
  accessMode: "ReadWriteOnce"
  enabled: true
  size: 512Mi
  storageClass: "openebs-glusterfs"
service:
  type: ClusterIP
env:
  open:
    STORAGE: local
    DISABLE_API: false
    ALLOW_OVERWRITE: true
